In [ ]:
import numpy as np

def Sigmoid(x):
    return 1/(1+np.exp(-x))

x=np.array([[0,0],
            [0,1],
            [1,0],
            [1,1]])

w1=np.array([[-2,  5,  4],
            [ 3,  6,  3]])
b1=np.array([ 2, -2, -5])

w2=np.array([[-4],
            [ 8],
            [-8]])

h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2))

print (h)
print (y)

[[0.88079708 0.11920292 0.00669285]
 [0.99330715 0.98201379 0.11920292]
 [0.5        0.95257413 0.26894142]
 [0.95257413 0.99987661 0.88079708]]
[[0.06766597]
 [0.94927397]
 [0.96979454]
 [0.0542867 ]]
