In [1]:
# xor1.ipynb
import numpy as np
def Sigmoid(x):
    return 1/(1+np.exp(-x))

lamda = 1
x=np.array([[0,0],[0,1],[1,0],[1,1]])
t=np.array([[0],[1],[1],[0]])

w1=2*np.random.rand(2,3)-1 # np.random.rand : 2*(0~1) 난수 -1 : -1 ~ 1
b1=2*np.random.rand(1,3)-1
w2=2*np.random.rand(3,1)-1

w1, b1, w2

(array([[-0.52963643,  0.15185911, -0.23282915],
        [ 0.54920834, -0.61321903,  0.52470622]]),
 array([[ 0.92564926, -0.13156051,  0.47812849]]),
 array([[-0.96955464],
        [-0.20934027],
        [ 0.30089271]]))

In [2]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2))
y, h.shape

(array([[0.35287193],
        [0.346088  ],
        [0.37368106],
        [0.36191115]]), (4, 3))

In [3]:
for i in range(1000):
    h=Sigmoid(np.dot(x,w1)+b1)
    y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication.
    deltaY= np.multiply(y-t,np.multiply(y,(1-y))) # multiply(): Multiply arguments element-wise.
    temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
    deltaH = deltaY * temp
    w2 = w2 - np.dot(h.transpose(),lamda*deltaY) # back propagation
    w1 = w1 - np.dot(x.transpose(),lamda*deltaH)
    b1 = b1- lamda*deltaH
print (y)
print(w1)
print(w2)
print(b1)

[[0.01823627]
 [0.98167801]
 [0.98130414]
 [0.0192214 ]]
[[-0.74210438  0.14801027 -0.46078876]
 [-0.0924064  -0.60758128  0.01966745]]
[[-4.86478475]
 [-0.29162494]
 [ 5.25641788]]
[[ 2.43330232 -0.00693528 -1.99178102]
 [-1.66096195 -0.2495539   2.30199928]
 [-1.23181515 -0.2590405   2.57907845]
 [ 2.87064572 -0.00792936 -1.85078108]]


In [4]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication.
deltaY= np.multiply(y-t,np.multiply(y,(1-y))) # multiply(): Multiply arguments element-wise.
temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
deltaH = deltaY * temp
w2 = w2 - np.dot(h.transpose(),lamda*deltaY) # back propagation
w1 = w1 - np.dot(x.transpose(),lamda*deltaH)
b1 = b1- lamda*deltaH

In [5]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication
h.shape, y.shape

((4, 3), (4, 1))

In [6]:
deltaY= np.multiply(y-t,np.multiply(y,(1-y)))
deltaY.shape

(4, 1)

In [7]:
temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
temp.shape

(4, 3)

In [8]:
deltaH = deltaY * temp
deltaH.shape

(4, 3)