In [19]:
import tensorflow as tf
import numpy as np

In [18]:
tf.__version__

'2.4.1'

In [20]:
x = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')
x, y

(array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=float32), array([[0.],
        [1.],
        [1.],
        [0.]], dtype=float32))

In [21]:
from tensorflow.keras import layers
model = tf.keras.Sequential()
model.add(layers.Dense(3, activation='sigmoid', input_dim=2))
model.add(layers.Dense(2, activation='sigmoid'))
model.add(layers.Dense(1, activation='sigmoid'))
sgd = tf.keras.optimizers.SGD(learning_rate=0.1)
model.compile(optimizer=sgd,loss='binary_crossentropy',metrics=['accuracy'])

In [22]:
model.fit(x, y, epochs=10000, verbose=0)
model.evaluate(x, y)

1/1 [==============================] - 0s 123ms/step - loss: 0.0057 - accuracy: 1.0000


[0.005686318036168814, 1.0]

In [23]:
predicted = model.predict(x)
predicted

array([[0.00652802],
       [0.9985379 ],
       [0.99090874],
       [0.00558424]], dtype=float32)

In [ ]:
import tensorflow  as tf
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')
from tensorflow.keras import layers
model = tf.keras.Sequential()
model.add(layers.Dense(3, activation='sigmoid', input_dim=2))
model.add(layers.Dense(1, activation='sigmoid'))
sgd= tf.keras.optimizers.SGD(learning_rate=0.1)
#model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])
model.compile(optimizer=sgd, loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x, y, epochs=10000, batch_size=4, verbose=0)
model.evaluate(x, y)
predicted = model.predict(x)
print(predicted)

1/1 [==============================] - 0s 95ms/step - loss: 0.0758 - accuracy: 1.0000
[[0.05624324]
 [0.90862167]
 [0.95199704]
 [0.09551615]]
